[package]
name = "fcwebserve"
version = "0.0.1"
authors = [ "Blake Loring <blake_l@parsed.uk>" ]

[dependencies]
rustc-serialize = "*"
staticfile = "*"
mount = "*"
time = "*"
hyper = "*"
iron = "*"

[dependencies.fccore]
path = "../core/"